services:
  db:
    image: postgres:15
    container_name: football-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: robinson00POST
      POSTGRES_DB: Football_stats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./PostgreSQL:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Football_stats"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    env_file:
      - .env
    container_name: football-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:robinson00POST@football-db:5432/Football_stats

volumes:
  postgres_data: